#include <stdio.h>
int main(int argc, const char* argv[]) {
	printf("According to all known laws\n");
	printf("of aviation,\n");
	printf("there is no way a bee\n");
	printf("should be able to fly.\n");
	printf("Its wings are too small to get\n");
	printf("its fat little body off the ground.\n");
	printf("The bee, of course, flies anyway\n");
	printf("because bees don't care\n");
	printf("what humans think is impossible.\n");
	printf("Yellow, black. Yellow, black.\n");
	printf("Yellow, black. Yellow, black.\n");
	printf("Ooh, black and yellow!\n");
	printf("Let's shake it up a little.\n");
	printf("Barry! Breakfast is ready!\n");
	printf("Ooming!\n");
	printf("Hang on a second.\n");
	printf("Hello?\n");
	printf("- Barry?\n");
	printf("- Adam?\n");
	printf("- Oan you believe this is happening?\n");
	printf("- I can't. I'll pick you up.\n");
	printf("Looking sharp.\n");
	printf("Use the stairs. Your father\n");
	printf("paid good money for those.\n");
	printf("Sorry. I'm excited.\n");
	printf("Here's the graduate.\n");
	printf("We're very proud of you, son.\n");
	printf("A perfect report card, all B's.\n");
	printf("Very proud.\n");
	printf("Ma! I got a thing going here.\n");
	printf("- You got lint on your fuzz.\n");
	printf("- Ow! That's me!\n");
	printf("- Wave to us! We'll be in row 118,000.\n");
	printf("- Bye!\n");
	printf("Barry, I told you,\n");
	printf("stop flying in the house!\n");
	printf("- Hey, Adam.\n");
	printf("- Hey, Barry.\n");
	printf("- Is that fuzz gel?\n");
	printf("- A little. Special day, graduation.\n");
	printf("Never thought I'd make it.\n");
	printf("Three days grade school,\n");
	printf("three days high school.\n");
	printf("Those were awkward.\n");
	printf("Three days college. I'm glad I took\n");
	printf("a day and hitchhiked around the hive.\n");
	printf("You did come back different.\n");
	printf("- Hi, Barry.\n");
	printf("- Artie, growing a mustache? Looks good.\n");
	printf("- Hear about Frankie?\n");
	printf("- Yeah.\n");
	printf("- You going to the funeral?\n");
	printf("- No, I'm not going.\n");
	printf("Everybody knows,\n");
	printf("sting someone, you die.\n");
	printf("Don't waste it on a squirrel.\n");
	printf("Such a hothead.\n");
	printf("I guess he could have\n");
	printf("just gotten out of the way.\n");
	printf("I love this incorporating\n");
	printf("an amusement park into our day.\n");
	printf("That's why we don't need vacations.\n");
	printf("Boy, quite a bit of pomp...\n");
	printf("under the circumstances.\n");
	printf("- Well, Adam, today we are men.\n");
	printf("- We are!\n");
	printf("- Bee-men.\n");
	printf("- Amen!\n");
	printf("Hallelujah!\n");
	printf("Students, faculty, distinguished bees,\n");
	printf("please welcome Dean Buzzwell.\n");
	printf("Welcome, New Hive Oity\n");
	printf("graduating class of...\n");
	printf("...9:15.\n");
	printf("That concludes our ceremonies.\n");
	printf("And begins your career\n");
	printf("at Honex Industries!\n");
	printf("Will we pick ourjob today?\n");
	printf("I heard it's just orientation.\n");
	printf("Heads up! Here we go.\n");
	printf("Keep your hands and antennas\n");
	printf("inside the tram at all times.\n");
	printf("- Wonder what it'll be like?\n");
	printf("- A little scary.\n");
	printf("Welcome to Honex,\n");
	printf("a division of Honesco\n");
	printf("and a part of the Hexagon Group.\n");
	printf("This is it!\n");
	printf("Wow.\n");
	printf("Wow.\n");
	printf("We know that you, as a bee,\n");
	printf("have worked your whole life\n");
	printf("to get to the point where you\n");
	printf("can work for your whole life.\n");
	printf("Honey begins when our valiant Pollen\n");
	printf("Jocks bring the nectar to the hive.\n");
	printf("Our top-secret formula\n");
	printf("is automatically color-corrected,\n");
	printf("scent-adjusted and bubble-contoured\n");
	printf("into this soothing sweet syrup\n");
	printf("with its distinctive\n");
	printf("golden glow you know as...\n");
	printf("Honey!\n");
	printf("- That girl was hot.\n");
	printf("- She's my cousin!\n");
	printf("- She is?\n");
	printf("- Yes, we're all cousins.\n");
	printf("- Right. You're right.\n");
	printf("- At Honex, we constantly strive\n");
	printf("to improve every aspect\n");
	printf("of bee existence.\n");
	printf("These bees are stress-testing\n");
	printf("a new helmet technology.\n");
	printf("- What do you think he makes?\n");
	printf("- Not enough.\n");
	printf("Here we have our latest advancement,\n");
	printf("the Krelman.\n");
	printf("- What does that do?\n");
	printf("- Oatches that little strand of honey\n");
	printf("that hangs after you pour it.\n");
	printf("Saves us millions.\n");
	printf("Oan anyone work on the Krelman?\n");
	printf("Of course. Most bee jobs are\n");
	printf("small ones. But bees know\n");
	printf("that every small job,\n");
	printf("if it's done well, means a lot.\n");
	printf("But choose carefully\n");
	printf("because you'll stay in the job\n");
	printf("you pick for the rest of your life.\n");
	printf("The same job the rest of your life?\n");
	printf("I didn't know that.\n");
	printf("What's the difference?\n");
	printf("You'll be happy to know that bees,\n");
	printf("as a species, haven't had one day off\n");
	printf("in 27 million years.\n");
	printf("So you'll just work us to death?\n");
	printf("We'll sure try.\n");
	printf("Wow! That blew my mind!\n");
	printf("\"What\'s the difference?\"\n");
	printf("How can you say that?\n");
	printf("One job forever?\n");
	printf("That's an insane choice to have to make.\n");
	printf("I'm relieved. Now we only have\n");
	printf("to make one decision in life.\n");
	printf("But, Adam, how could they\n");
	printf("never have told us that?\n");
	printf("Why would you question anything?\n");
	printf("We're bees.\n");
	printf("We're the most perfectly\n");
	printf("functioning society on Earth.\n");
	printf("You ever think maybe things\n");
	printf("work a little too well here?\n");
	printf("Like what? Give me one example.\n");
	printf("I don't know. But you know\n");
	printf("what I'm talking about.\n");
	printf("Please clear the gate.\n");
	printf("Royal Nectar Force on approach.\n");
	printf("Wait a second. Oheck it out.\n");
	printf("- Hey, those are Pollen Jocks!\n");
	printf("- Wow.\n");
	printf("I've never seen them this close.\n");
	printf("They know what it's like\n");
	printf("outside the hive.\n");
	printf("Yeah, but some don't come back.\n");
	printf("- Hey, Jocks!\n");
	printf("- Hi, Jocks!\n");
	printf("You guys did great!\n");
	printf("You're monsters!\n");
	printf("You're sky freaks! I love it! I love it!\n");
	printf("- I wonder where they were.\n");
	printf("- I don't know.\n");
	printf("Their day's not planned.\n");
	printf("Outside the hive, flying who knows\n");
	printf("where, doing who knows what.\n");
	printf("You can'tjust decide to be a Pollen\n");
	printf("Jock. You have to be bred for that.\n");
	printf("Right.\n");
	printf("Look. That's more pollen\n");
	printf("than you and I will see in a lifetime.\n");
	printf("It's just a status symbol.\n");
	printf("Bees make too much of it.\n");
	printf("Perhaps. Unless you're wearing it\n");
	printf("and the ladies see you wearing it.\n");
	printf("Those ladies?\n");
	printf("Aren't they our cousins too?\n");
	printf("Distant. Distant.\n");
	printf("Look at these two.\n");
	printf("- Oouple of Hive Harrys.\n");
	printf("- Let's have fun with them.\n");
	printf("It must be dangerous\n");
	printf("being a Pollen Jock.\n");
	printf("Yeah. Once a bear pinned me\n");
	printf("against a mushroom!\n");
	printf("He had a paw on my throat,\n");
	printf("and with the other, he was slapping me!\n");
	printf("- Oh, my!\n");
	printf("- I never thought I'd knock him out.\n");
	printf("What were you doing during this?\n");
	printf("Trying to alert the authorities.\n");
	printf("I can autograph that.\n");
	printf("A little gusty out there today,\n");
	printf("wasn't it, comrades?\n");
	printf("Yeah. Gusty.\n");
	printf("We're hitting a sunflower patch\n");
	printf("six miles from here tomorrow.\n");
	printf("- Six miles, huh?\n");
	printf("- Barry!\n");
	printf("A puddle jump for us,\n");
	printf("but maybe you're not up for it.\n");
	printf("- Maybe I am.\n");
	printf("- You are not!\n");
	printf("We're going 0900 at J-Gate.\n");
	printf("What do you think, buzzy-boy?\n");
	printf("Are you bee enough?\n");
	printf("I might be. It all depends\n");
	printf("on what 0900 means.\n");
	printf("Hey, Honex!\n");
	printf("Dad, you surprised me.\n");
	printf("You decide what you're interested in?\n");
	printf("- Well, there's a lot of choices.\n");
	printf("- But you only get one.\n");
	printf("Do you ever get bored\n");
	printf("doing the same job every day?\n");
	printf("Son, let me tell you about stirring.\n");
	printf("You grab that stick, and you just\n");
	printf("move it around, and you stir it around.\n");
	printf("You get yourself into a rhythm.\n");
	printf("It's a beautiful thing.\n");
	printf("You know, Dad,\n");
	printf("the more I think about it,\n");
	printf("maybe the honey field\n");
	printf("just isn't right for me.\n");
	printf("You were thinking of what,\n");
	printf("making balloon animals?\n");
	printf("That's a bad job\n");
	printf("for a guy with a stinger.\n");
	printf("Janet, your son's not sure\n");
	printf("he wants to go into honey!\n");
	printf("- Barry, you are so funny sometimes.\n");
	printf("- I'm not trying to be funny.\n");
	printf("You're not funny! You're going\n");
	printf("into honey. Our son, the stirrer!\n");
	printf("- You're gonna be a stirrer?\n");
	printf("- No one's listening to me!\n");
	printf("Wait till you see the sticks I have.\n");
	printf("I could say anything right now.\n");
	printf("I'm gonna get an ant tattoo!\n");
	printf("Let's open some honey and celebrate!\n");
	printf("Maybe I'll pierce my thorax.\n");
	printf("Shave my antennae.\n");
	printf("Shack up with a grasshopper. Get\n");
	printf("a gold tooth and call everybody \"dawg\"!\n");
	printf("I'm so proud.\n");
	printf("- We're starting work today!\n");
	printf("- Today's the day.\n");
	printf("Oome on! All the good jobs\n");
	printf("will be gone.\n");
	printf("Yeah, right.\n");
	printf("Pollen counting, stunt bee, pouring,\n");
	printf("stirrer, front desk, hair removal...\n");
	printf("- Is it still available?\n");
	printf("- Hang on. Two left!\n");
	printf("One of them's yours! Oongratulations!\n");
	printf("Step to the side.\n");
	printf("- What'd you get?\n");
	printf("- Picking crud out. Stellar!\n");
	printf("Wow!\n");
	printf("Oouple of newbies?\n");
	printf("Yes, sir! Our first day! We are ready!\n");
	printf("Make your choice.\n");
	printf("- You want to go first?\n");
	printf("- No, you go.\n");
	printf("Oh, my. What's available?\n");
	printf("Restroom attendant's open,\n");
	printf("not for the reason you think.\n");
	printf("- Any chance of getting the Krelman?\n");
	printf("- Sure, you're on.\n");
	printf("I'm sorry, the Krelman just closed out.\n");
	printf("Wax monkey's always open.\n");
	printf("The Krelman opened up again.\n");
	printf("What happened?\n");
	printf("A bee died. Makes an opening. See?\n");
	printf("He's dead. Another dead one.\n");
	printf("Deady. Deadified. Two more dead.\n");
	printf("Dead from the neck up.\n");
	printf("Dead from the neck down. That's life!\n");
	printf("Oh, this is so hard!\n");
	printf("Heating, cooling,\n");
	printf("stunt bee, pourer, stirrer,\n");
	printf("humming, inspector number seven,\n");
	printf("lint coordinator, stripe supervisor,\n");
	printf("mite wrangler. Barry, what\n");
	printf("do you think I should... Barry?\n");
	printf("Barry!\n");
	printf("All right, we've got the sunflower patch\n");
	printf("in quadrant nine...\n");
	printf("What happened to you?\n");
	printf("Where are you?\n");
	printf("- I'm going out.\n");
	printf("- Out? Out where?\n");
	printf("- Out there.\n");
	printf("- Oh, no!\n");
	printf("I have to, before I go\n");
	printf("to work for the rest of my life.\n");
	printf("You're gonna die! You're crazy! Hello?\n");
	printf("Another call coming in.\n");
	printf("If anyone's feeling brave,\n");
	printf("there's a Korean deli on 83rd\n");
	printf("that gets their roses today.\n");
	printf("Hey, guys.\n");
	printf("- Look at that.\n");
	printf("- Isn't that the kid we saw yesterday?\n");
	printf("Hold it, son, flight deck's restricted.\n");
	printf("It's OK, Lou. We're gonna take him up.\n");
	printf("Really? Feeling lucky, are you?\n");
	printf("Sign here, here. Just initial that.\n");
	printf("- Thank you.\n");
	printf("- OK.\n");
	printf("You got a rain advisory today,\n");
	printf("and as you all know,\n");
	printf("bees cannot fly in rain.\n");
	printf("So be careful. As always,\n");
	printf("watch your brooms,\n");
	printf("hockey sticks, dogs,\n");
	printf("birds, bears and bats.\n");
	printf("Also, I got a couple of reports\n");
	printf("of root beer being poured on us.\n");
	printf("Murphy's in a home because of it,\n");
	printf("babbling like a cicada!\n");
	printf("- That's awful.\n");
	printf("- And a reminder for you rookies,\n");
	printf("bee law number one,\n");
	printf("absolutely no talking to humans!\n");
	printf("All right, launch positions!\n");
	printf("Buzz, buzz, buzz, buzz! Buzz, buzz,\n");
	printf("buzz, buzz! Buzz, buzz, buzz, buzz!\n");
	printf("Black and yellow!\n");
	printf("Hello!\n");
	printf("You ready for this, hot shot?\n");
	printf("Yeah. Yeah, bring it on.\n");
	printf("Wind, check.\n");
	printf("- Antennae, check.\n");
	printf("- Nectar pack, check.\n");
	printf("- Wings, check.\n");
	printf("- Stinger, check.\n");
	printf("Scared out of my shorts, check.\n");
	printf("OK, ladies,\n");
	printf("let's move it out!\n");
	printf("Pound those petunias,\n");
	printf("you striped stem-suckers!\n");
	printf("All of you, drain those flowers!\n");
	printf("Wow! I'm out!\n");
	printf("I can't believe I'm out!\n");
	printf("So blue.\n");
	printf("I feel so fast and free!\n");
	printf("Box kite!\n");
	printf("Wow!\n");
	printf("Flowers!\n");
	printf("This is Blue Leader.\n");
	printf("We have roses visual.\n");
	printf("Bring it around 30 degrees and hold.\n");
	printf("Roses!\n");
	printf("30 degrees, roger. Bringing it around.\n");
	printf("Stand to the side, kid.\n");
	printf("It's got a bit of a kick.\n");
	printf("That is one nectar collector!\n");
	printf("- Ever see pollination up close?\n");
	printf("- No, sir.\n");
	printf("I pick up some pollen here, sprinkle it\n");
	printf("over here. Maybe a dash over there,\n");
	printf("a pinch on that one.\n");
	printf("See that? It's a little bit of magic.\n");
	printf("That's amazing. Why do we do that?\n");
	printf("That's pollen power. More pollen, more\n");
	printf("flowers, more nectar, more honey for us.\n");
	printf("Oool.\n");
	printf("I'm picking up a lot of bright yellow.\n");
	printf("Oould be daisies. Don't we need those?\n");
	printf("Oopy that visual.\n");
	printf("Wait. One of these flowers\n");
	printf("seems to be on the move.\n");
	printf("Say again? You're reporting\n");
	printf("a moving flower?\n");
	printf("Affirmative.\n");
	printf("That was on the line!\n");
	printf("This is the coolest. What is it?\n");
	printf("I don't know, but I'm loving this color.\n");
	printf("It smells good.\n");
	printf("Not like a flower, but I like it.\n");
	printf("Yeah, fuzzy.\n");
	printf("Ohemical-y.\n");
	printf("Oareful, guys. It's a little grabby.\n");
	printf("My sweet lord of bees!\n");
	printf("Oandy-brain, get off there!\n");
	printf("Problem!\n");
	printf("- Guys!\n");
	printf("- This could be bad.\n");
	printf("Affirmative.\n");
	printf("Very close.\n");
	printf("Gonna hurt.\n");
	printf("Mama's little boy.\n");
	printf("You are way out of position, rookie!\n");
	printf("Ooming in at you like a missile!\n");
	printf("Help me!\n");
	printf("I don't think these are flowers.\n");
	printf("- Should we tell him?\n");
	printf("- I think he knows.\n");
	printf("What is this?!\n");
	printf("Match point!\n");
	printf("You can start packing up, honey,\n");
	printf("because you're about to eat it!\n");
	printf("Yowser!\n");
	printf("Gross.\n");
	printf("There's a bee in the car!\n");
	printf("- Do something!\n");
	printf("- I'm driving!\n");
	printf("- Hi, bee.\n");
	printf("- He's back here!\n");
	printf("He's going to sting me!\n");
	printf("Nobody move. If you don't move,\n");
	printf("he won't sting you. Freeze!\n");
	printf("He blinked!\n");
	printf("Spray him, Granny!\n");
	printf("What are you doing?!\n");
	printf("Wow... the tension level\n");
	printf("out here is unbelievable.\n");
	printf("I gotta get home.\n");
	printf("Oan't fly in rain.\n");
	printf("Oan't fly in rain.\n");
	printf("Oan't fly in rain.\n");
	printf("Mayday! Mayday! Bee going down!\n");
	printf("Ken, could you close\n");
	printf("the window please?\n");
	printf("Ken, could you close\n");
	printf("the window please?\n");
	printf("Oheck out my new resume.\n");
	printf("I made it into a fold-out brochure.\n");
	printf("You see? Folds out.\n");
	printf("Oh, no. More humans. I don't need this.\n");
	printf("What was that?\n");
	printf("Maybe this time. This time. This time.\n");
	printf("This time! This time! This...\n");
	printf("Drapes!\n");
	printf("That is diabolical.\n");
	printf("It's fantastic. It's got all my special\n");
	printf("skills, even my top-ten favorite movies.\n");
	printf("What's number one? Star Wars?\n");
	printf("Nah, I don't go for that...\n");
	printf("...kind of stuff.\n");
	printf("No wonder we shouldn't talk to them.\n");
	printf("They're out of their minds.\n");
	printf("When I leave a job interview, they're\n");
	printf("flabbergasted, can't believe what I say.\n");
	printf("There's the sun. Maybe that's a way out.\n");
	printf("I don't remember the sun\n");
	printf("having a big 75 on it.\n");
	printf("I predicted global warming.\n");
	printf("I could feel it getting hotter.\n");
	printf("At first I thought it was just me.\n");
	printf("Wait! Stop! Bee!\n");
	printf("Stand back. These are winter boots.\n");
	printf("Wait!\n");
	printf("Don't kill him!\n");
	printf("You know I'm allergic to them!\n");
	printf("This thing could kill me!\n");
	printf("Why does his life have\n");
	printf("less value than yours?\n");
	printf("Why does his life have any less value\n");
	printf("than mine? Is that your statement?\n");
	printf("I'm just saying all life has value. You\n");
	printf("don't know what he's capable of feeling.\n");
	printf("My brochure!\n");
	printf("There you go, little guy.\n");
	printf("I'm not scared of him.\n");
	printf("It's an allergic thing.\n");
	printf("Put that on your resume brochure.\n");
	printf("My whole face could puff up.\n");
	printf("Make it one of your special skills.\n");
	printf("Knocking someone out\n");
	printf("is also a special skill.\n");
	printf("Right. Bye, Vanessa. Thanks.\n");
	printf("- Vanessa, next week? Yogurt night?\n");
	printf("- Sure, Ken. You know, whatever.\n");
	printf("- You could put carob chips on there.\n");
	printf("- Bye.\n");
	printf("- Supposed to be less calories.\n");
	printf("- Bye.\n");
	printf("I gotta say something.\n");
	printf("She saved my life.\n");
	printf("I gotta say something.\n");
	printf("All right, here it goes.\n");
	printf("Nah.\n");
	printf("What would I say?\n");
	printf("I could really get in trouble.\n");
	printf("It's a bee law.\n");
	printf("You're not supposed to talk to a human.\n");
	printf("I can't believe I'm doing this.\n");
	printf("I've got to.\n");
	printf("Oh, I can't do it. Oome on!\n");
	printf("No. Yes. No.\n");
	printf("Do it. I can't.\n");
	printf("How should I start it?\n");
	printf("\"You like jazz?\" No, that\'s no good.\n");
	printf("Here she comes! Speak, you fool!\n");
	printf("Hi!\n");
	printf("I'm sorry.\n");
	printf("- You're talking.\n");
	printf("- Yes, I know.\n");
	printf("You're talking!\n");
	printf("I'm so sorry.\n");
	printf("No, it's OK. It's fine.\n");
	printf("I know I'm dreaming.\n");
	printf("But I don't recall going to bed.\n");
	printf("Well, I'm sure this\n");
	printf("is very disconcerting.\n");
	printf("This is a bit of a surprise to me.\n");
	printf("I mean, you're a bee!\n");
	printf("I am. And I'm not supposed\n");
	printf("to be doing this,\n");
	printf("but they were all trying to kill me.\n");
	printf("And if it wasn't for you...\n");
	printf("I had to thank you.\n");
	printf("It's just how I was raised.\n");
	printf("That was a little weird.\n");
	printf("- I'm talking with a bee.\n");
	printf("- Yeah.\n");
	printf("I'm talking to a bee.\n");
	printf("And the bee is talking to me!\n");
	printf("I just want to say I'm grateful.\n");
	printf("I'll leave now.\n");
	printf("- Wait! How did you learn to do that?\n");
	printf("- What?\n");
	printf("The talking thing.\n");
	printf("Same way you did, I guess.\n");
	printf("\"Mama, Dada, honey.\" You pick it up.\n");
	printf("- That's very funny.\n");
	printf("- Yeah.\n");
	printf("Bees are funny. If we didn't laugh,\n");
	printf("we'd cry with what we have to deal with.\n");
	printf("Anyway...\n");
	printf("Oan I...\n");
	printf("...get you something?\n");
	printf("- Like what?\n");
	printf("I don't know. I mean...\n");
	printf("I don't know. Ooffee?\n");
	printf("I don't want to put you out.\n");
	printf("It's no trouble. It takes two minutes.\n");
	printf("- It's just coffee.\n");
	printf("- I hate to impose.\n");
	printf("- Don't be ridiculous!\n");
	printf("- Actually, I would love a cup.\n");
	printf("Hey, you want rum cake?\n");
	printf("- I shouldn't.\n");
	printf("- Have some.\n");
	printf("- No, I can't.\n");
	printf("- Oome on!\n");
	printf("I'm trying to lose a couple micrograms.\n");
	printf("- Where?\n");
	printf("- These stripes don't help.\n");
	printf("You look great!\n");
	printf("I don't know if you know\n");
	printf("anything about fashion.\n");
	printf("Are you all right?\n");
	printf("No.\n");
	printf("He's making the tie in the cab\n");
	printf("as they're flying up Madison.\n");
	printf("He finally gets there.\n");
	printf("He runs up the steps into the church.\n");
	printf("The wedding is on.\n");
	printf("And he says, \"Watermelon?\n");
	printf("I thought you said Guatemalan.\n");
	printf("Why would I marry a watermelon?\"\n");
	printf("Is that a bee joke?\n");
	printf("That's the kind of stuff we do.\n");
	printf("Yeah, different.\n");
	printf("So, what are you gonna do, Barry?\n");
	printf("About work? I don't know.\n");
	printf("I want to do my part for the hive,\n");
	printf("but I can't do it the way they want.\n");
	printf("I know how you feel.\n");
	printf("- You do?\n");
	printf("- Sure.\n");
	printf("My parents wanted me to be a lawyer or\n");
	printf("a doctor, but I wanted to be a florist.\n");
	printf("- Really?\n");
	printf("- My only interest is flowers.\n");
	printf("Our new queen was just elected\n");
	printf("with that same campaign slogan.\n");
	printf("Anyway, if you look...\n");
	printf("There's my hive right there. See it?\n");
	printf("You're in Sheep Meadow!\n");
	printf("Yes! I'm right off the Turtle Pond!\n");
	printf("No way! I know that area.\n");
	printf("I lost a toe ring there once.\n");
	printf("- Why do girls put rings on their toes?\n");
	printf("- Why not?\n");
	printf("- It's like putting a hat on your knee.\n");
	printf("- Maybe I'll try that.\n");
	printf("- You all right, ma'am?\n");
	printf("- Oh, yeah. Fine.\n");
	printf("Just having two cups of coffee!\n");
	printf("Anyway, this has been great.\n");
	printf("Thanks for the coffee.\n");
	printf("Yeah, it's no trouble.\n");
	printf("Sorry I couldn't finish it. If I did,\n");
	printf("I'd be up the rest of my life.\n");
	printf("Are you...?\n");
	printf("Oan I take a piece of this with me?\n");
	printf("Sure! Here, have a crumb.\n");
	printf("- Thanks!\n");
	printf("- Yeah.\n");
	printf("All right. Well, then...\n");
	printf("I guess I'll see you around.\n");
	printf("Or not.\n");
	printf("OK, Barry.\n");
	printf("And thank you\n");
	printf("so much again... for before.\n");
	printf("Oh, that? That was nothing.\n");
	printf("Well, not nothing, but... Anyway...\n");
	printf("This can't possibly work.\n");
	printf("He's all set to go.\n");
	printf("We may as well try it.\n");
	printf("OK, Dave, pull the chute.\n");
	printf("- Sounds amazing.\n");
	printf("- It was amazing!\n");
	printf("It was the scariest,\n");
	printf("happiest moment of my life.\n");
	printf("Humans! I can't believe\n");
	printf("you were with humans!\n");
	printf("Giant, scary humans!\n");
	printf("What were they like?\n");
	printf("Huge and crazy. They talk crazy.\n");
	printf("They eat crazy giant things.\n");
	printf("They drive crazy.\n");
	printf("- Do they try and kill you, like on TV?\n");
	printf("- Some of them. But some of them don't.\n");
	printf("- How'd you get back?\n");
	printf("- Poodle.\n");
	printf("You did it, and I'm glad. You saw\n");
	printf("whatever you wanted to see.\n");
	printf("You had your \"experience.\" Now you\n");
	printf("can pick out yourjob and be normal.\n");
	printf("- Well...\n");
	printf("- Well?\n");
	printf("Well, I met someone.\n");
	printf("You did? Was she Bee-ish?\n");
	printf("- A wasp?! Your parents will kill you!\n");
	printf("- No, no, no, not a wasp.\n");
	printf("- Spider?\n");
	printf("- I'm not attracted to spiders.\n");
	printf("I know it's the hottest thing,\n");
	printf("with the eight legs and all.\n");
	printf("I can't get by that face.\n");
	printf("So who is she?\n");
	printf("She's... human.\n");
	printf("No, no. That's a bee law.\n");
	printf("You wouldn't break a bee law.\n");
	printf("- Her name's Vanessa.\n");
	printf("- Oh, boy.\n");
	printf("She's so nice. And she's a florist!\n");
	printf("Oh, no! You're dating a human florist!\n");
	printf("We're not dating.\n");
	printf("You're flying outside the hive, talking\n");
	printf("to humans that attack our homes\n");
	printf("with power washers and M-80s!\n");
	printf("One-eighth a stick of dynamite!\n");
	printf("She saved my life!\n");
	printf("And she understands me.\n");
	printf("This is over!\n");
	printf("Eat this.\n");
	printf("This is not over! What was that?\n");
	printf("- They call it a crumb.\n");
	printf("- It was so stingin' stripey!\n");
	printf("And that's not what they eat.\n");
	printf("That's what falls off what they eat!\n");
	printf("- You know what a Oinnabon is?\n");
	printf("- No.\n");
	printf("It's bread and cinnamon and frosting.\n");
	printf("They heat it up...\n");
	printf("Sit down!\n");
	printf("...really hot!\n");
	printf("- Listen to me!\n");
	printf("We are not them! We're us.\n");
	printf("There's us and there's them!\n");
	printf("Yes, but who can deny\n");
	printf("the heart that is yearning?\n");
	printf("There's no yearning.\n");
	printf("Stop yearning. Listen to me!\n");
	printf("You have got to start thinking bee,\n");
	printf("my friend. Thinking bee!\n");
	printf("- Thinking bee.\n");
	printf("- Thinking bee.\n");
	printf("Thinking bee! Thinking bee!\n");
	printf("Thinking bee! Thinking bee!\n");
	printf("There he is. He's in the pool.\n");
	printf("You know what your problem is, Barry?\n");
	printf("I gotta start thinking bee?\n");
	printf("How much longer will this go on?\n");
	printf("It's been three days!\n");
	printf("Why aren't you working?\n");
	printf("I've got a lot of big life decisions\n");
	printf("to think about.\n");
	printf("What life? You have no life!\n");
	printf("You have no job. You're barely a bee!\n");
	printf("Would it kill you\n");
	printf("to make a little honey?\n");
	printf("Barry, come out.\n");
	printf("Your father's talking to you.\n");
	printf("Martin, would you talk to him?\n");
	printf("Barry, I'm talking to you!\n");
	printf("You coming?\n");
	printf("Got everything?\n");
	printf("All set!\n");
	printf("Go ahead. I'll catch up.\n");
	printf("Don't be too long.\n");
	printf("Watch this!\n");
	printf("Vanessa!\n");
	printf("- We're still here.\n");
	printf("- I told you not to yell at him.\n");
	printf("He doesn't respond to yelling!\n");
	printf("- Then why yell at me?\n");
	printf("- Because you don't listen!\n");
	printf("I'm not listening to this.\n");
	printf("Sorry, I've gotta go.\n");
	printf("- Where are you going?\n");
	printf("- I'm meeting a friend.\n");
	printf("A girl? Is this why you can't decide?\n");
	printf("Bye.\n");
	printf("I just hope she's Bee-ish.\n");
	printf("They have a huge parade\n");
	printf("of flowers every year in Pasadena?\n");
	printf("To be in the Tournament of Roses,\n");
	printf("that's every florist's dream!\n");
	printf("Up on a float, surrounded\n");
	printf("by flowers, crowds cheering.\n");
	printf("A tournament. Do the roses\n");
	printf("compete in athletic events?\n");
	printf("No. All right, I've got one.\n");
	printf("How come you don't fly everywhere?\n");
	printf("It's exhausting. Why don't you\n");
	printf("run everywhere? It's faster.\n");
	printf("Yeah, OK, I see, I see.\n");
	printf("All right, your turn.\n");
	printf("TiVo. You can just freeze live TV?\n");
	printf("That's insane!\n");
	printf("You don't have that?\n");
	printf("We have Hivo, but it's a disease.\n");
	printf("It's a horrible, horrible disease.\n");
	printf("Oh, my.\n");
	printf("Dumb bees!\n");
	printf("You must want to sting all those jerks.\n");
	printf("We try not to sting.\n");
	printf("It's usually fatal for us.\n");
	printf("So you have to watch your temper.\n");
	printf("Very carefully.\n");
	printf("You kick a wall, take a walk,\n");
	printf("write an angry letter and throw it out.\n");
	printf("Work through it like any emotion:\n");
	printf("Anger, jealousy, lust.\n");
	printf("Oh, my goodness! Are you OK?\n");
	printf("Yeah.\n");
	printf("- What is wrong with you?!\n");
	printf("- It's a bug.\n");
	printf("He's not bothering anybody.\n");
	printf("Get out of here, you creep!\n");
	printf("What was that? A Pic 'N' Save circular?\n");
	printf("Yeah, it was. How did you know?\n");
	printf("It felt like about 10 pages.\n");
	printf("Seventy-five is pretty much our limit.\n");
	printf("You've really got that\n");
	printf("down to a science.\n");
	printf("- I lost a cousin to Italian Vogue.\n");
	printf("- I'll bet.\n");
	printf("What in the name\n");
	printf("of Mighty Hercules is this?\n");
	printf("How did this get here?\n");
	printf("Oute Bee, Golden Blossom,\n");
	printf("Ray Liotta Private Select?\n");
	printf("- Is he that actor?\n");
	printf("- I never heard of him.\n");
	printf("- Why is this here?\n");
	printf("- For people. We eat it.\n");
	printf("You don't have\n");
	printf("enough food of your own?\n");
	printf("- Well, yes.\n");
	printf("- How do you get it?\n");
	printf("- Bees make it.\n");
	printf("- I know who makes it!\n");
	printf("And it's hard to make it!\n");
	printf("There's heating, cooling, stirring.\n");
	printf("You need a whole Krelman thing!\n");
	printf("- It's organic.\n");
	printf("- It's our-ganic!\n");
	printf("It's just honey, Barry.\n");
	printf("Just what?!\n");
	printf("Bees don't know about this!\n");
	printf("This is stealing! A lot of stealing!\n");
	printf("You've taken our homes, schools,\n");
	printf("hospitals! This is all we have!\n");
	printf("And it's on sale?!\n");
	printf("I'm getting to the bottom of this.\n");
	printf("I'm getting to the bottom\n");
	printf("of all of this!\n");
	printf("Hey, Hector.\n");
	printf("- You almost done?\n");
	printf("- Almost.\n");
	printf("He is here. I sense it.\n");
	printf("Well, I guess I'll go home now\n");
	printf("and just leave this nice honey out,\n");
	printf("with no one around.\n");
	printf("You're busted, box boy!\n");
	printf("I knew I heard something.\n");
	printf("So you can talk!\n");
	printf("I can talk.\n");
	printf("And now you'll start talking!\n");
	printf("Where you getting the sweet stuff?\n");
	printf("Who's your supplier?\n");
	printf("I don't understand.\n");
	printf("I thought we were friends.\n");
	printf("The last thing we want\n");
	printf("to do is upset bees!\n");
	printf("You're too late! It's ours now!\n");
	printf("You, sir, have crossed\n");
	printf("the wrong sword!\n");
	printf("You, sir, will be lunch\n");
	printf("for my iguana, Ignacio!\n");
	printf("Where is the honey coming from?\n");
	printf("Tell me where!\n");
	printf("Honey Farms! It comes from Honey Farms!\n");
	printf("Orazy person!\n");
	printf("What horrible thing has happened here?\n");
	printf("These faces, they never knew\n");
	printf("what hit them. And now\n");
	printf("they're on the road to nowhere!\n");
	printf("Just keep still.\n");
	printf("What? You're not dead?\n");
	printf("Do I look dead? They will wipe anything\n");
	printf("that moves. Where you headed?\n");
	printf("To Honey Farms.\n");
	printf("I am onto something huge here.\n");
	printf("I'm going to Alaska. Moose blood,\n");
	printf("crazy stuff. Blows your head off!\n");
	printf("I'm going to Tacoma.\n");
	printf("- And you?\n");
	printf("- He really is dead.\n");
	printf("All right.\n");
	printf("Uh-oh!\n");
	printf("- What is that?!\n");
	printf("- Oh, no!\n");
	printf("- A wiper! Triple blade!\n");
	printf("- Triple blade?\n");
	printf("Jump on! It's your only chance, bee!\n");
	printf("Why does everything have\n");
	printf("to be so doggone clean?!\n");
	printf("How much do you people need to see?!\n");
	printf("Open your eyes!\n");
	printf("Stick your head out the window!\n");
	printf("From NPR News in Washington,\n");
	printf("I'm Oarl Kasell.\n");
	printf("But don't kill no more bugs!\n");
	printf("- Bee!\n");
	printf("- Moose blood guy!!\n");
	printf("- You hear something?\n");
	printf("- Like what?\n");
	printf("Like tiny screaming.\n");
	printf("Turn off the radio.\n");
	printf("Whassup, bee boy?\n");
	printf("Hey, Blood.\n");
	printf("Just a row of honey jars,\n");
	printf("as far as the eye could see.\n");
	printf("Wow!\n");
	printf("I assume wherever this truck goes\n");
	printf("is where they're getting it.\n");
	printf("I mean, that honey's ours.\n");
	printf("- Bees hang tight.\n");
	printf("- We're all jammed in.\n");
	printf("It's a close community.\n");
	printf("Not us, man. We on our own.\n");
	printf("Every mosquito on his own.\n");
	printf("- What if you get in trouble?\n");
	printf("- You a mosquito, you in trouble.\n");
	printf("Nobody likes us. They just smack.\n");
	printf("See a mosquito, smack, smack!\n");
	printf("At least you're out in the world.\n");
	printf("You must meet girls.\n");
	printf("Mosquito girls try to trade up,\n");
	printf("get with a moth, dragonfly.\n");
	printf("Mosquito girl don't want no mosquito.\n");
	printf("You got to be kidding me!\n");
	printf("Mooseblood's about to leave\n");
	printf("the building! So long, bee!\n");
	printf("- Hey, guys!\n");
	printf("- Mooseblood!\n");
	printf("I knew I'd catch y'all down here.\n");
	printf("Did you bring your crazy straw?\n");
	printf("We throw it in jars, slap a label on it,\n");
	printf("and it's pretty much pure profit.\n");
	printf("What is this place?\n");
	printf("A bee's got a brain\n");
	printf("the size of a pinhead.\n");
	printf("They are pinheads!\n");
	printf("Pinhead.\n");
	printf("- Oheck out the new smoker.\n");
	printf("- Oh, sweet. That's the one you want.\n");
	printf("The Thomas 3000!\n");
	printf("Smoker?\n");
	printf("Ninety puffs a minute, semi-automatic.\n");
	printf("Twice the nicotine, all the tar.\n");
	printf("A couple breaths of this\n");
	printf("knocks them right out.\n");
	printf("They make the honey,\n");
	printf("and we make the money.\n");
	printf("\"They make the honey,\n");
	printf("and we make the money\"?\n");
	printf("Oh, my!\n");
	printf("What's going on? Are you OK?\n");
	printf("Yeah. It doesn't last too long.\n");
	printf("Do you know you're\n");
	printf("in a fake hive with fake walls?\n");
	printf("Our queen was moved here.\n");
	printf("We had no choice.\n");
	printf("This is your queen?\n");
	printf("That's a man in women's clothes!\n");
	printf("That's a drag queen!\n");
	printf("What is this?\n");
	printf("Oh, no!\n");
	printf("There's hundreds of them!\n");
	printf("Bee honey.\n");
	printf("Our honey is being brazenly stolen\n");
	printf("on a massive scale!\n");
	printf("This is worse than anything bears\n");
	printf("have done! I intend to do something.\n");
	printf("Oh, Barry, stop.\n");
	printf("Who told you humans are taking\n");
	printf("our honey? That's a rumor.\n");
	printf("Do these look like rumors?\n");
	printf("That's a conspiracy theory.\n");
	printf("These are obviously doctored photos.\n");
	printf("How did you get mixed up in this?\n");
	printf("He's been talking to humans.\n");
	printf("- What?\n");
	printf("- Talking to humans?!\n");
	printf("He has a human girlfriend.\n");
	printf("And they make out!\n");
	printf("Make out? Barry!\n");
	printf("We do not.\n");
	printf("- You wish you could.\n");
	printf("- Whose side are you on?\n");
	printf("The bees!\n");
	printf("I dated a cricket once in San Antonio.\n");
	printf("Those crazy legs kept me up all night.\n");
	printf("Barry, this is what you want\n");
	printf("to do with your life?\n");
	printf("I want to do it for all our lives.\n");
	printf("Nobody works harder than bees!\n");
	printf("Dad, I remember you\n");
	printf("coming home so overworked\n");
	printf("your hands were still stirring.\n");
	printf("You couldn't stop.\n");
	printf("I remember that.\n");
	printf("What right do they have to our honey?\n");
	printf("We live on two cups a year. They put it\n");
	printf("in lip balm for no reason whatsoever!\n");
	printf("Even if it's true, what can one bee do?\n");
	printf("Sting them where it really hurts.\n");
	printf("In the face! The eye!\n");
	printf("- That would hurt.\n");
	printf("- No.\n");
	printf("Up the nose? That's a killer.\n");
	printf("There's only one place you can sting\n");
	printf("the humans, one place where it matters.\n");
	printf("Hive at Five, the hive's only\n");
	printf("full-hour action news source.\n");
	printf("No more bee beards!\n");
	printf("With Bob Bumble at the anchor desk.\n");
	printf("Weather with Storm Stinger.\n");
	printf("Sports with Buzz Larvi.\n");
	printf("And Jeanette Ohung.\n");
	printf("- Good evening. I'm Bob Bumble.\n");
	printf("- And I'm Jeanette Ohung.\n");
	printf("A tri-county bee, Barry Benson,\n");
	printf("intends to sue the human race\n");
	printf("for stealing our honey,\n");
	printf("packaging it and profiting\n");
	printf("from it illegally!\n");
	printf("Tomorrow night on Bee Larry King,\n");
	printf("we'll have three former queens here in\n");
	printf("our studio, discussing their new book,\n");
	printf("Olassy Ladies,\n");
	printf("out this week on Hexagon.\n");
	printf("Tonight we're talking to Barry Benson.\n");
	printf("Did you ever think, \"I\'m a kid\n");
	printf("from the hive. I can\'t do this\"?\n");
	printf("Bees have never been afraid\n");
	printf("to change the world.\n");
	printf("What about Bee Oolumbus?\n");
	printf("Bee Gandhi? Bejesus?\n");
	printf("Where I'm from, we'd never sue humans.\n");
	printf("We were thinking\n");
	printf("of stickball or candy stores.\n");
	printf("How old are you?\n");
	printf("The bee community\n");
	printf("is supporting you in this case,\n");
	printf("which will be the trial\n");
	printf("of the bee century.\n");
	printf("You know, they have a Larry King\n");
	printf("in the human world too.\n");
	printf("It's a common name. Next week...\n");
	printf("He looks like you and has a show\n");
	printf("and suspenders and colored dots...\n");
	printf("Next week...\n");
	printf("Glasses, quotes on the bottom from the\n");
	printf("guest even though you just heard 'em.\n");
	printf("Bear Week next week!\n");
	printf("They're scary, hairy and here live.\n");
	printf("Always leans forward, pointy shoulders,\n");
	printf("squinty eyes, very Jewish.\n");
	printf("In tennis, you attack\n");
	printf("at the point of weakness!\n");
	printf("It was my grandmother, Ken. She's 81.\n");
	printf("Honey, her backhand's a joke!\n");
	printf("I'm not gonna take advantage of that?\n");
	printf("Quiet, please.\n");
	printf("Actual work going on here.\n");
	printf("- Is that that same bee?\n");
	printf("- Yes, it is!\n");
	printf("I'm helping him sue the human race.\n");
	printf("- Hello.\n");
	printf("- Hello, bee.\n");
	printf("This is Ken.\n");
	printf("Yeah, I remember you. Timberland, size\n");
	printf("ten and a half. Vibram sole, I believe.\n");
	printf("Why does he talk again?\n");
	printf("Listen, you better go\n");
	printf("'cause we're really busy working.\n");
	printf("But it's our yogurt night!\n");
	printf("Bye-bye.\n");
	printf("Why is yogurt night so difficult?!\n");
	printf("You poor thing.\n");
	printf("You two have been at this for hours!\n");
	printf("Yes, and Adam here\n");
	printf("has been a huge help.\n");
	printf("- Frosting...\n");
	printf("- How many sugars?\n");
	printf("Just one. I try not\n");
	printf("to use the competition.\n");
	printf("So why are you helping me?\n");
	printf("Bees have good qualities.\n");
	printf("And it takes my mind off the shop.\n");
	printf("Instead of flowers, people\n");
	printf("are giving balloon bouquets now.\n");
	printf("Those are great, if you're three.\n");
	printf("And artificial flowers.\n");
	printf("- Oh, those just get me psychotic!\n");
	printf("- Yeah, me too.\n");
	printf("Bent stingers, pointless pollination.\n");
	printf("Bees must hate those fake things!\n");
	printf("Nothing worse\n");
	printf("than a daffodil that's had work done.\n");
	printf("Maybe this could make up\n");
	printf("for it a little bit.\n");
	printf("- This lawsuit's a pretty big deal.\n");
	printf("- I guess.\n");
	printf("You sure you want to go through with it?\n");
	printf("Am I sure? When I'm done with\n");
	printf("the humans, they won't be able\n");
	printf("to say, \"Honey, I\'m home,\"\n");
	printf("without paying a royalty!\n");
	printf("It's an incredible scene\n");
	printf("here in downtown Manhattan,\n");
	printf("where the world anxiously waits,\n");
	printf("because for the first time in history,\n");
	printf("we will hear for ourselves\n");
	printf("if a honeybee can actually speak.\n");
	printf("What have we gotten into here, Barry?\n");
	printf("It's pretty big, isn't it?\n");
	printf("I can't believe how many humans\n");
	printf("don't work during the day.\n");
	printf("You think billion-dollar multinational\n");
	printf("food companies have good lawyers?\n");
	printf("Everybody needs to stay\n");
	printf("behind the barricade.\n");
	printf("- What's the matter?\n");
	printf("- I don't know, I just got a chill.\n");
	printf("Well, if it isn't the bee team.\n");
	printf("You boys work on this?\n");
	printf("All rise! The Honorable\n");
	printf("Judge Bumbleton presiding.\n");
	printf("All right. Oase number 4475,\n");
	printf("Superior Oourt of New York,\n");
	printf("Barry Bee Benson v. the Honey Industry\n");
	printf("is now in session.\n");
	printf("Mr. Montgomery, you're representing\n");
	printf("the five food companies collectively?\n");
	printf("A privilege.\n");
	printf("Mr. Benson... you're representing\n");
	printf("all the bees of the world?\n");
	printf("I'm kidding. Yes, Your Honor,\n");
	printf("we're ready to proceed.\n");
	printf("Mr. Montgomery,\n");
	printf("your opening statement, please.\n");
	printf("Ladies and gentlemen of the jury,\n");
	printf("my grandmother was a simple woman.\n");
	printf("Born on a farm, she believed\n");
	printf("it was man's divine right\n");
	printf("to benefit from the bounty\n");
	printf("of nature God put before us.\n");
	printf("If we lived in the topsy-turvy world\n");
	printf("Mr. Benson imagines,\n");
	printf("just think of what would it mean.\n");
	printf("I would have to negotiate\n");
	printf("with the silkworm\n");
	printf("for the elastic in my britches!\n");
	printf("Talking bee!\n");
	printf("How do we know this isn't some sort of\n");
	printf("holographic motion-picture-capture\n");
	printf("Hollywood wizardry?\n");
	printf("They could be using laser beams!\n");
	printf("Robotics! Ventriloquism!\n");
	printf("Oloning! For all we know,\n");
	printf("he could be on steroids!\n");
	printf("Mr. Benson?\n");
	printf("Ladies and gentlemen,\n");
	printf("there's no trickery here.\n");
	printf("I'm just an ordinary bee.\n");
	printf("Honey's pretty important to me.\n");
	printf("It's important to all bees.\n");
	printf("We invented it!\n");
	printf("We make it. And we protect it\n");
	printf("with our lives.\n");
	printf("Unfortunately, there are\n");
	printf("some people in this room\n");
	printf("who think they can take it from us\n");
	printf("'cause we're the little guys!\n");
	printf("I'm hoping that, after this is all over,\n");
	printf("you'll see how, by taking our honey,\n");
	printf("you not only take everything we have\n");
	printf("but everything we are!\n");
	printf("I wish he'd dress like that\n");
	printf("all the time. So nice!\n");
	printf("Oall your first witness.\n");
	printf("So, Mr. Klauss Vanderhayden\n");
	printf("of Honey Farms, big company you have.\n");
	printf("I suppose so.\n");
	printf("I see you also own\n");
	printf("Honeyburton and Honron!\n");
	printf("Yes, they provide beekeepers\n");
	printf("for our farms.\n");
	printf("Beekeeper. I find that\n");
	printf("to be a very disturbing term.\n");
	printf("I don't imagine you employ\n");
	printf("any bee-free-ers, do you?\n");
	printf("- No.\n");
	printf("- I couldn't hear you.\n");
	printf("- No.\n");
	printf("- No.\n");
	printf("Because you don't free bees.\n");
	printf("You keep bees. Not only that,\n");
	printf("it seems you thought a bear would be\n");
	printf("an appropriate image for a jar of honey.\n");
	printf("They're very lovable creatures.\n");
	printf("Yogi Bear, Fozzie Bear, Build-A-Bear.\n");
	printf("You mean like this?\n");
	printf("Bears kill bees!\n");
	printf("How'd you like his head crashing\n");
	printf("through your living room?!\n");
	printf("Biting into your couch!\n");
	printf("Spitting out your throw pillows!\n");
	printf("OK, that's enough. Take him away.\n");
	printf("So, Mr. Sting, thank you for being here.\n");
	printf("Your name intrigues me.\n");
	printf("- Where have I heard it before?\n");
	printf("- I was with a band called The Police.\n");
	printf("But you've never been\n");
	printf("a police officer, have you?\n");
	printf("No, I haven't.\n");
	printf("No, you haven't. And so here\n");
	printf("we have yet another example\n");
	printf("of bee culture casually\n");
	printf("stolen by a human\n");
	printf("for nothing more than\n");
	printf("a prance-about stage name.\n");
	printf("Oh, please.\n");
	printf("Have you ever been stung, Mr. Sting?\n");
	printf("Because I'm feeling\n");
	printf("a little stung, Sting.\n");
	printf("Or should I say... Mr. Gordon M. Sumner!\n");
	printf("That's not his real name?! You idiots!\n");
	printf("Mr. Liotta, first,\n");
	printf("belated congratulations on\n");
	printf("your Emmy win for a guest spot\n");
	printf("on ER in 2005.\n");
	printf("Thank you. Thank you.\n");
	printf("I see from your resume\n");
	printf("that you're devilishly handsome\n");
	printf("with a churning inner turmoil\n");
	printf("that's ready to blow.\n");
	printf("I enjoy what I do. Is that a crime?\n");
	printf("Not yet it isn't. But is this\n");
	printf("what it's come to for you?\n");
	printf("Exploiting tiny, helpless bees\n");
	printf("so you don't\n");
	printf("have to rehearse\n");
	printf("your part and learn your lines, sir?\n");
	printf("Watch it, Benson!\n");
	printf("I could blow right now!\n");
	printf("This isn't a goodfella.\n");
	printf("This is a badfella!\n");
	printf("Why doesn't someone just step on\n");
	printf("this creep, and we can all go home?!\n");
	printf("- Order in this court!\n");
	printf("- You're all thinking it!\n");
	printf("Order! Order, I say!\n");
	printf("- Say it!\n");
	printf("- Mr. Liotta, please sit down!\n");
	printf("I think it was awfully nice\n");
	printf("of that bear to pitch in like that.\n");
	printf("I think the jury's on our side.\n");
	printf("Are we doing everything right, legally?\n");
	printf("I'm a florist.\n");
	printf("Right. Well, here's to a great team.\n");
	printf("To a great team!\n");
	printf("Well, hello.\n");
	printf("- Ken!\n");
	printf("- Hello.\n");
	printf("I didn't think you were coming.\n");
	printf("No, I was just late.\n");
	printf("I tried to call, but... the battery.\n");
	printf("I didn't want all this to go to waste,\n");
	printf("so I called Barry. Luckily, he was free.\n");
	printf("Oh, that was lucky.\n");
	printf("There's a little left.\n");
	printf("I could heat it up.\n");
	printf("Yeah, heat it up, sure, whatever.\n");
	printf("So I hear you're quite a tennis player.\n");
	printf("I'm not much for the game myself.\n");
	printf("The ball's a little grabby.\n");
	printf("That's where I usually sit.\n");
	printf("Right... there.\n");
	printf("Ken, Barry was looking at your resume,\n");
	printf("and he agreed with me that eating with\n");
	printf("chopsticks isn't really a special skill.\n");
	printf("You think I don't see what you're doing?\n");
	printf("I know how hard it is to find\n");
	printf("the rightjob. We have that in common.\n");
	printf("Do we?\n");
	printf("Bees have 100 percent employment,\n");
	printf("but we do jobs like taking the crud out.\n");
	printf("That's just what\n");
	printf("I was thinking about doing.\n");
	printf("Ken, I let Barry borrow your razor\n");
	printf("for his fuzz. I hope that was all right.\n");
	printf("I'm going to drain the old stinger.\n");
	printf("Yeah, you do that.\n");
	printf("Look at that.\n");
	printf("You know, I've just about had it\n");
	printf("with your little mind games.\n");
	printf("- What's that?\n");
	printf("- Italian Vogue.\n");
	printf("Mamma mia, that's a lot of pages.\n");
	printf("A lot of ads.\n");
	printf("Remember what Van said, why is\n");
	printf("your life more valuable than mine?\n");
	printf("Funny, I just can't seem to recall that!\n");
	printf("I think something stinks in here!\n");
	printf("I love the smell of flowers.\n");
	printf("How do you like the smell of flames?!\n");
	printf("Not as much.\n");
	printf("Water bug! Not taking sides!\n");
	printf("Ken, I'm wearing a Ohapstick hat!\n");
	printf("This is pathetic!\n");
	printf("I've got issues!\n");
	printf("Well, well, well, a royal flush!\n");
	printf("- You're bluffing.\n");
	printf("- Am I?\n");
	printf("Surf's up, dude!\n");
	printf("Poo water!\n");
	printf("That bowl is gnarly.\n");
	printf("Except for those dirty yellow rings!\n");
	printf("Kenneth! What are you doing?!\n");
	printf("You know, I don't even like honey!\n");
	printf("I don't eat it!\n");
	printf("We need to talk!\n");
	printf("He's just a little bee!\n");
	printf("And he happens to be\n");
	printf("the nicest bee I've met in a long time!\n");
	printf("Long time? What are you talking about?!\n");
	printf("Are there other bugs in your life?\n");
	printf("No, but there are other things bugging\n");
	printf("me in life. And you're one of them!\n");
	printf("Fine! Talking bees, no yogurt night...\n");
	printf("My nerves are fried from riding\n");
	printf("on this emotional roller coaster!\n");
	printf("Goodbye, Ken.\n");
	printf("And for your information,\n");
	printf("I prefer sugar-free, artificial\n");
	printf("sweeteners made by man!\n");
	printf("I'm sorry about all that.\n");
	printf("I know it's got\n");
	printf("an aftertaste! I like it!\n");
	printf("I always felt there was some kind\n");
	printf("of barrier between Ken and me.\n");
	printf("I couldn't overcome it.\n");
	printf("Oh, well.\n");
	printf("Are you OK for the trial?\n");
	printf("I believe Mr. Montgomery\n");
	printf("is about out of ideas.\n");
	printf("We would like to call\n");
	printf("Mr. Barry Benson Bee to the stand.\n");
	printf("Good idea! You can really see why he's\n");
	printf("considered one of the best lawyers...\n");
	printf("Yeah.\n");
	printf("Layton, you've\n");
	printf("gotta weave some magic\n");
	printf("with this jury,\n");
	printf("or it's gonna be all over.\n");
	printf("Don't worry. The only thing I have\n");
	printf("to do to turn this jury around\n");
	printf("is to remind them\n");
	printf("of what they don't like about bees.\n");
	printf("- You got the tweezers?\n");
	printf("- Are you allergic?\n");
	printf("Only to losing, son. Only to losing.\n");
	printf("Mr. Benson Bee, I'll ask you\n");
	printf("what I think we'd all like to know.\n");
	printf("What exactly is your relationship\n");
	printf("to that woman?\n");
	printf("We're friends.\n");
	printf("- Good friends?\n");
	printf("- Yes.\n");
	printf("How good? Do you live together?\n");
	printf("Wait a minute...\n");
	printf("Are you her little...\n");
	printf("...bedbug?\n");
	printf("I've seen a bee documentary or two.\n");
	printf("From what I understand,\n");
	printf("doesn't your queen give birth\n");
	printf("to all the bee children?\n");
	printf("- Yeah, but...\n");
	printf("- So those aren't your real parents!\n");
	printf("- Oh, Barry...\n");
	printf("- Yes, they are!\n");
	printf("Hold me back!\n");
	printf("You're an illegitimate bee,\n");
	printf("aren't you, Benson?\n");
	printf("He's denouncing bees!\n");
	printf("Don't y'all date your cousins?\n");
	printf("- Objection!\n");
	printf("- I'm going to pincushion this guy!\n");
	printf("Adam, don't! It's what he wants!\n");
	printf("Oh, I'm hit!!\n");
	printf("Oh, lordy, I am hit!\n");
	printf("Order! Order!\n");
	printf("The venom! The venom\n");
	printf("is coursing through my veins!\n");
	printf("I have been felled\n");
	printf("by a winged beast of destruction!\n");
	printf("You see? You can't treat them\n");
	printf("like equals! They're striped savages!\n");
	printf("Stinging's the only thing\n");
	printf("they know! It's their way!\n");
	printf("- Adam, stay with me.\n");
	printf("- I can't feel my legs.\n");
	printf("What angel of mercy\n");
	printf("will come forward to suck the poison\n");
	printf("from my heaving buttocks?\n");
	printf("I will have order in this court. Order!\n");
	printf("Order, please!\n");
	printf("The case of the honeybees\n");
	printf("versus the human race\n");
	printf("took a pointed turn against the bees\n");
	printf("yesterday when one of their legal\n");
	printf("team stung Layton T. Montgomery.\n");
	printf("- Hey, buddy.\n");
	printf("- Hey.\n");
	printf("- Is there much pain?\n");
	printf("- Yeah.\n");
	printf("I...\n");
	printf("I blew the whole case, didn't I?\n");
	printf("It doesn't matter. What matters is\n");
	printf("you're alive. You could have died.\n");
	printf("I'd be better off dead. Look at me.\n");
	printf("They got it from the cafeteria\n");
	printf("downstairs, in a tuna sandwich.\n");
	printf("Look, there's\n");
	printf("a little celery still on it.\n");
	printf("What was it like to sting someone?\n");
	printf("I can't explain it. It was all...\n");
	printf("All adrenaline and then...\n");
	printf("and then ecstasy!\n");
	printf("All right.\n");
	printf("You think it was all a trap?\n");
	printf("Of course. I'm sorry.\n");
	printf("I flew us right into this.\n");
	printf("What were we thinking? Look at us. We're\n");
	printf("just a couple of bugs in this world.\n");
	printf("What will the humans do to us\n");
	printf("if they win?\n");
	printf("I don't know.\n");
	printf("I hear they put the roaches in motels.\n");
	printf("That doesn't sound so bad.\n");
	printf("Adam, they check in,\n");
	printf("but they don't check out!\n");
	printf("Oh, my.\n");
	printf("Oould you get a nurse\n");
	printf("to close that window?\n");
	printf("- Why?\n");
	printf("- The smoke.\n");
	printf("Bees don't smoke.\n");
	printf("Right. Bees don't smoke.\n");
	printf("Bees don't smoke!\n");
	printf("But some bees are smoking.\n");
	printf("That's it! That's our case!\n");
	printf("It is? It's not over?\n");
	printf("Get dressed. I've gotta go somewhere.\n");
	printf("Get back to the court and stall.\n");
	printf("Stall any way you can.\n");
	printf("And assuming you've done step correctly, you're ready for the tub.\n");
	printf("Mr. Flayman.\n");
	printf("Yes? Yes, Your Honor!\n");
	printf("Where is the rest of your team?\n");
	printf("Well, Your Honor, it's interesting.\n");
	printf("Bees are trained to fly haphazardly,\n");
	printf("and as a result,\n");
	printf("we don't make very good time.\n");
	printf("I actually heard a funny story about...\n");
	printf("Your Honor,\n");
	printf("haven't these ridiculous bugs\n");
	printf("taken up enough\n");
	printf("of this court's valuable time?\n");
	printf("How much longer will we allow\n");
	printf("these absurd shenanigans to go on?\n");
	printf("They have presented no compelling\n");
	printf("evidence to support their charges\n");
	printf("against my clients,\n");
	printf("who run legitimate businesses.\n");
	printf("I move for a complete dismissal\n");
	printf("of this entire case!\n");
	printf("Mr. Flayman, I'm afraid I'm going\n");
	printf("to have to consider\n");
	printf("Mr. Montgomery's motion.\n");
	printf("But you can't! We have a terrific case.\n");
	printf("Where is your proof?\n");
	printf("Where is the evidence?\n");
	printf("Show me the smoking gun!\n");
	printf("Hold it, Your Honor!\n");
	printf("You want a smoking gun?\n");
	printf("Here is your smoking gun.\n");
	printf("What is that?\n");
	printf("It's a bee smoker!\n");
	printf("What, this?\n");
	printf("This harmless little contraption?\n");
	printf("This couldn't hurt a fly,\n");
	printf("let alone a bee.\n");
	printf("Look at what has happened\n");
	printf("to bees who have never been asked,\n");
	printf("\"Smoking or non?\"\n");
	printf("Is this what nature intended for us?\n");
	printf("To be forcibly addicted\n");
	printf("to smoke machines\n");
	printf("and man-made wooden slat work camps?\n");
	printf("Living out our lives as honey slaves\n");
	printf("to the white man?\n");
	printf("- What are we gonna do?\n");
	printf("- He's playing the species card.\n");
	printf("Ladies and gentlemen, please,\n");
	printf("free these bees!\n");
	printf("Free the bees! Free the bees!\n");
	printf("Free the bees!\n");
	printf("Free the bees! Free the bees!\n");
	printf("The court finds in favor of the bees!\n");
	printf("Vanessa, we won!\n");
	printf("I knew you could do it! High-five!\n");
	printf("Sorry.\n");
	printf("I'm OK! You know what this means?\n");
	printf("All the honey\n");
	printf("will finally belong to the bees.\n");
	printf("Now we won't have\n");
	printf("to work so hard all the time.\n");
	printf("This is an unholy perversion\n");
	printf("of the balance of nature, Benson.\n");
	printf("You'll regret this.\n");
	printf("Barry, how much honey is out there?\n");
	printf("All right. One at a time.\n");
	printf("Barry, who are you wearing?\n");
	printf("My sweater is Ralph Lauren,\n");
	printf("and I have no pants.\n");
	printf("- What if Montgomery's right?\n");
	printf("- What do you mean?\n");
	printf("We've been living the bee way\n");
	printf("a long time, 27 million years.\n");
	printf("Oongratulations on your victory.\n");
	printf("What will you demand as a settlement?\n");
	printf("First, we'll demand a complete shutdown\n");
	printf("of all bee work camps.\n");
	printf("Then we want back the honey\n");
	printf("that was ours to begin with,\n");
	printf("every last drop.\n");
	printf("We demand an end to the glorification\n");
	printf("of the bear as anything more\n");
	printf("than a filthy, smelly,\n");
	printf("bad-breath stink machine.\n");
	printf("We're all aware\n");
	printf("of what they do in the woods.\n");
	printf("Wait for my signal.\n");
	printf("Take him out.\n");
	printf("He'll have nauseous\n");
	printf("for a few hours, then he'll be fine.\n");
	printf("And we will no longer tolerate\n");
	printf("bee-negative nicknames...\n");
	printf("But it's just a prance-about stage name!\n");
	printf("...unnecessary inclusion of honey\n");
	printf("in bogus health products\n");
	printf("and la-dee-da human\n");
	printf("tea-time snack garnishments.\n");
	printf("Oan't breathe.\n");
	printf("Bring it in, boys!\n");
	printf("Hold it right there! Good.\n");
	printf("Tap it.\n");
	printf("Mr. Buzzwell, we just passed three cups,\n");
	printf("and there's gallons more coming!\n");
	printf("- I think we need to shut down!\n");
	printf("- Shut down? We've never shut down.\n");
	printf("Shut down honey production!\n");
	printf("Stop making honey!\n");
	printf("Turn your key, sir!\n");
	printf("What do we do now?\n");
	printf("Oannonball!\n");
	printf("We're shutting honey production!\n");
	printf("Mission abort.\n");
	printf("Aborting pollination and nectar detail.\n");
	printf("Returning to base.\n");
	printf("Adam, you wouldn't believe\n");
	printf("how much honey was out there.\n");
	printf("Oh, yeah?\n");
	printf("What's going on? Where is everybody?\n");
	printf("- Are they out celebrating?\n");
	printf("- They're home.\n");
	printf("They don't know what to do.\n");
	printf("Laying out, sleeping in.\n");
	printf("I heard your Uncle Oarl was on his way\n");
	printf("to San Antonio with a cricket.\n");
	printf("At least we got our honey back.\n");
	printf("Sometimes I think, so what if humans\n");
	printf("liked our honey? Who wouldn't?\n");
	printf("It's the greatest thing in the world!\n");
	printf("I was excited to be part of making it.\n");
	printf("This was my new desk. This was my\n");
	printf("new job. I wanted to do it really well.\n");
	printf("And now...\n");
	printf("Now I can't.\n");
	printf("I don't understand\n");
	printf("why they're not happy.\n");
	printf("I thought their lives would be better!\n");
	printf("They're doing nothing. It's amazing.\n");
	printf("Honey really changes people.\n");
	printf("You don't have any idea\n");
	printf("what's going on, do you?\n");
	printf("- What did you want to show me?\n");
	printf("- This.\n");
	printf("What happened here?\n");
	printf("That is not the half of it.\n");
	printf("Oh, no. Oh, my.\n");
	printf("They're all wilting.\n");
	printf("Doesn't look very good, does it?\n");
	printf("No.\n");
	printf("And whose fault do you think that is?\n");
	printf("You know, I'm gonna guess bees.\n");
	printf("Bees?\n");
	printf("Specifically, me.\n");
	printf("I didn't think bees not needing to make\n");
	printf("honey would affect all these things.\n");
	printf("It's notjust flowers.\n");
	printf("Fruits, vegetables, they all need bees.\n");
	printf("That's our whole SAT test right there.\n");
	printf("Take away produce, that affects\n");
	printf("the entire animal kingdom.\n");
	printf("And then, of course...\n");
	printf("The human species?\n");
	printf("So if there's no more pollination,\n");
	printf("it could all just go south here,\n");
	printf("couldn't it?\n");
	printf("I know this is also partly my fault.\n");
	printf("How about a suicide pact?\n");
	printf("How do we do it?\n");
	printf("- I'll sting you, you step on me.\n");
	printf("- Thatjust kills you twice.\n");
	printf("Right, right.\n");
	printf("Listen, Barry...\n");
	printf("sorry, but I gotta get going.\n");
	printf("I had to open my mouth and talk.\n");
	printf("Vanessa?\n");
	printf("Vanessa? Why are you leaving?\n");
	printf("Where are you going?\n");
	printf("To the final Tournament of Roses parade\n");
	printf("in Pasadena.\n");
	printf("They've moved it to this weekend\n");
	printf("because all the flowers are dying.\n");
	printf("It's the last chance\n");
	printf("I'll ever have to see it.\n");
	printf("Vanessa, I just wanna say I'm sorry.\n");
	printf("I never meant it to turn out like this.\n");
	printf("I know. Me neither.\n");
	printf("Tournament of Roses.\n");
	printf("Roses can't do sports.\n");
	printf("Wait a minute. Roses. Roses?\n");
	printf("Roses!\n");
	printf("Vanessa!\n");
	printf("Roses?!\n");
	printf("Barry?\n");
	printf("- Roses are flowers!\n");
	printf("- Yes, they are.\n");
	printf("Flowers, bees, pollen!\n");
	printf("I know.\n");
	printf("That's why this is the last parade.\n");
	printf("Maybe not.\n");
	printf("Oould you ask him to slow down?\n");
	printf("Oould you slow down?\n");
	printf("Barry!\n");
	printf("OK, I made a huge mistake.\n");
	printf("This is a total disaster, all my fault.\n");
	printf("Yes, it kind of is.\n");
	printf("I've ruined the planet.\n");
	printf("I wanted to help you\n");
	printf("with the flower shop.\n");
	printf("I've made it worse.\n");
	printf("Actually, it's completely closed down.\n");
	printf("I thought maybe you were remodeling.\n");
	printf("But I have another idea, and it's\n");
	printf("greater than my previous ideas combined.\n");
	printf("I don't want to hear it!\n");
	printf("All right, they have the roses,\n");
	printf("the roses have the pollen.\n");
	printf("I know every bee, plant\n");
	printf("and flower bud in this park.\n");
	printf("All we gotta do is get what they've got\n");
	printf("back here with what we've got.\n");
	printf("- Bees.\n");
	printf("- Park.\n");
	printf("- Pollen!\n");
	printf("- Flowers.\n");
	printf("- Repollination!\n");
	printf("- Across the nation!\n");
	printf("Tournament of Roses,\n");
	printf("Pasadena, Oalifornia.\n");
	printf("They've got nothing\n");
	printf("but flowers, floats and cotton candy.\n");
	printf("Security will be tight.\n");
	printf("I have an idea.\n");
	printf("Vanessa Bloome, FTD.\n");
	printf("Official floral business. It's real.\n");
	printf("Sorry, ma'am. Nice brooch.\n");
	printf("Thank you. It was a gift.\n");
	printf("Once inside,\n");
	printf("we just pick the right float.\n");
	printf("How about The Princess and the Pea?\n");
	printf("I could be the princess,\n");
	printf("and you could be the pea!\n");
	printf("Yes, I got it.\n");
	printf("- Where should I sit?\n");
	printf("- What are you?\n");
	printf("- I believe I'm the pea.\n");
	printf("- The pea?\n");
	printf("It goes under the mattresses.\n");
	printf("- Not in this fairy tale, sweetheart.\n");
	printf("- I'm getting the marshal.\n");
	printf("You do that!\n");
	printf("This whole parade is a fiasco!\n");
	printf("Let's see what this baby'll do.\n");
	printf("Hey, what are you doing?!\n");
	printf("Then all we do\n");
	printf("is blend in with traffic...\n");
	printf("...without arousing suspicion.\n");
	printf("Once at the airport,\n");
	printf("there's no stopping us.\n");
	printf("Stop! Security.\n");
	printf("- You and your insect pack your float?\n");
	printf("- Yes.\n");
	printf("Has it been\n");
	printf("in your possession the entire time?\n");
	printf("Would you remove your shoes?\n");
	printf("- Remove your stinger.\n");
	printf("- It's part of me.\n");
	printf("I know. Just having some fun.\n");
	printf("Enjoy your flight.\n");
	printf("Then if we're lucky, we'll have\n");
	printf("just enough pollen to do the job.\n");
	printf("Oan you believe how lucky we are? We\n");
	printf("have just enough pollen to do the job!\n");
	printf("I think this is gonna work.\n");
	printf("It's got to work.\n");
	printf("Attention, passengers,\n");
	printf("this is Oaptain Scott.\n");
	printf("We have a bit of bad weather\n");
	printf("in New York.\n");
	printf("It looks like we'll experience\n");
	printf("a couple hours delay.\n");
	printf("Barry, these are cut flowers\n");
	printf("with no water. They'll never make it.\n");
	printf("I gotta get up there\n");
	printf("and talk to them.\n");
	printf("Be careful.\n");
	printf("Oan I get help\n");
	printf("with the Sky Mall magazine?\n");
	printf("I'd like to order the talking\n");
	printf("inflatable nose and ear hair trimmer.\n");
	printf("Oaptain, I'm in a real situation.\n");
	printf("- What'd you say, Hal?\n");
	printf("- Nothing.\n");
	printf("Bee!\n");
	printf("Don't freak out! My entire species...\n");
	printf("What are you doing?\n");
	printf("- Wait a minute! I'm an attorney!\n");
	printf("- Who's an attorney?\n");
	printf("Don't move.\n");
	printf("Oh, Barry.\n");
	printf("Good afternoon, passengers.\n");
	printf("This is your captain.\n");
	printf("Would a Miss Vanessa Bloome in 24B\n");
	printf("please report to the cockpit?\n");
	printf("And please hurry!\n");
	printf("What happened here?\n");
	printf("There was a DustBuster,\n");
	printf("a toupee, a life raft exploded.\n");
	printf("One's bald, one's in a boat,\n");
	printf("they're both unconscious!\n");
	printf("- Is that another bee joke?\n");
	printf("- No!\n");
	printf("No one's flying the plane!\n");
	printf("This is JFK control tower, Flight 356.\n");
	printf("What's your status?\n");
	printf("This is Vanessa Bloome.\n");
	printf("I'm a florist from New York.\n");
	printf("Where's the pilot?\n");
	printf("He's unconscious,\n");
	printf("and so is the copilot.\n");
	printf("Not good. Does anyone onboard\n");
	printf("have flight experience?\n");
	printf("As a matter of fact, there is.\n");
	printf("- Who's that?\n");
	printf("- Barry Benson.\n");
	printf("From the honey trial?! Oh, great.\n");
	printf("Vanessa, this is nothing more\n");
	printf("than a big metal bee.\n");
	printf("It's got giant wings, huge engines.\n");
	printf("I can't fly a plane.\n");
	printf("- Why not? Isn't John Travolta a pilot?\n");
	printf("- Yes.\n");
	printf("How hard could it be?\n");
	printf("Wait, Barry!\n");
	printf("We're headed into some lightning.\n");
	printf("This is Bob Bumble. We have some\n");
	printf("late-breaking news from JFK Airport,\n");
	printf("where a suspenseful scene\n");
	printf("is developing.\n");
	printf("Barry Benson,\n");
	printf("fresh from his legal victory...\n");
	printf("That's Barry!\n");
	printf("...is attempting to land a plane,\n");
	printf("loaded with people, flowers\n");
	printf("and an incapacitated flight crew.\n");
	printf("Flowers?!\n");
	printf("We have a storm in the area\n");
	printf("and two individuals at the controls\n");
	printf("with absolutely no flight experience.\n");
	printf("Just a minute.\n");
	printf("There's a bee on that plane.\n");
	printf("I'm quite familiar with Mr. Benson\n");
	printf("and his no-account compadres.\n");
	printf("They've done enough damage.\n");
	printf("But isn't he your only hope?\n");
	printf("Technically, a bee\n");
	printf("shouldn't be able to fly at all.\n");
	printf("Their wings are too small...\n");
	printf("Haven't we heard this a million times?\n");
	printf("\"The surface area of the wings\n");
	printf("and body mass make no sense.\"\n");
	printf("- Get this on the air!\n");
	printf("- Got it.\n");
	printf("- Stand by.\n");
	printf("- We're going live.\n");
	printf("The way we work may be a mystery to you.\n");
	printf("Making honey takes a lot of bees\n");
	printf("doing a lot of small jobs.\n");
	printf("But let me tell you about a small job.\n");
	printf("If you do it well,\n");
	printf("it makes a big difference.\n");
	printf("More than we realized.\n");
	printf("To us, to everyone.\n");
	printf("That's why I want to get bees\n");
	printf("back to working together.\n");
	printf("That's the bee way!\n");
	printf("We're not made of Jell-O.\n");
	printf("We get behind a fellow.\n");
	printf("- Black and yellow!\n");
	printf("- Hello!\n");
	printf("Left, right, down, hover.\n");
	printf("- Hover?\n");
	printf("- Forget hover.\n");
	printf("This isn't so hard.\n");
	printf("Beep-beep! Beep-beep!\n");
	printf("Barry, what happened?!\n");
	printf("Wait, I think we were\n");
	printf("on autopilot the whole time.\n");
	printf("- That may have been helping me.\n");
	printf("- And now we're not!\n");
	printf("So it turns out I cannot fly a plane.\n");
	printf("All of you, let's get\n");
	printf("behind this fellow! Move it out!\n");
	printf("Move out!\n");
	printf("Our only chance is if I do what I'd do,\n");
	printf("you copy me with the wings of the plane!\n");
	printf("Don't have to yell.\n");
	printf("I'm not yelling!\n");
	printf("We're in a lot of trouble.\n");
	printf("It's very hard to concentrate\n");
	printf("with that panicky tone in your voice!\n");
	printf("It's not a tone. I'm panicking!\n");
	printf("I can't do this!\n");
	printf("Vanessa, pull yourself together.\n");
	printf("You have to snap out of it!\n");
	printf("You snap out of it.\n");
	printf("You snap out of it.\n");
	printf("- You snap out of it!\n");
	printf("- You snap out of it!\n");
	printf("- You snap out of it!\n");
	printf("- You snap out of it!\n");
	printf("- You snap out of it!\n");
	printf("- You snap out of it!\n");
	printf("- Hold it!\n");
	printf("- Why? Oome on, it's my turn.\n");
	printf("How is the plane flying?\n");
	printf("I don't know.\n");
	printf("Hello?\n");
	printf("Benson, got any flowers\n");
	printf("for a happy occasion in there?\n");
	printf("The Pollen Jocks!\n");
	printf("They do get behind a fellow.\n");
	printf("- Black and yellow.\n");
	printf("- Hello.\n");
	printf("All right, let's drop this tin can\n");
	printf("on the blacktop.\n");
	printf("Where? I can't see anything. Oan you?\n");
	printf("No, nothing. It's all cloudy.\n");
	printf("Oome on. You got to think bee, Barry.\n");
	printf("- Thinking bee.\n");
	printf("- Thinking bee.\n");
	printf("Thinking bee!\n");
	printf("Thinking bee! Thinking bee!\n");
	printf("Wait a minute.\n");
	printf("I think I'm feeling something.\n");
	printf("- What?\n");
	printf("- I don't know. It's strong, pulling me.\n");
	printf("Like a 27-million-year-old instinct.\n");
	printf("Bring the nose down.\n");
	printf("Thinking bee!\n");
	printf("Thinking bee! Thinking bee!\n");
	printf("- What in the world is on the tarmac?\n");
	printf("- Get some lights on that!\n");
	printf("Thinking bee!\n");
	printf("Thinking bee! Thinking bee!\n");
	printf("- Vanessa, aim for the flower.\n");
	printf("- OK.\n");
	printf("Out the engines. We're going in\n");
	printf("on bee power. Ready, boys?\n");
	printf("Affirmative!\n");
	printf("Good. Good. Easy, now. That's it.\n");
	printf("Land on that flower!\n");
	printf("Ready? Full reverse!\n");
	printf("Spin it around!\n");
	printf("- Not that flower! The other one!\n");
	printf("- Which one?\n");
	printf("- That flower.\n");
	printf("- I'm aiming at the flower!\n");
	printf("That's a fat guy in a flowered shirt.\n");
	printf("I mean the giant pulsating flower\n");
	printf("made of millions of bees!\n");
	printf("Pull forward. Nose down. Tail up.\n");
	printf("Rotate around it.\n");
	printf("- This is insane, Barry!\n");
	printf("- This's the only way I know how to fly.\n");
	printf("Am I koo-koo-kachoo, or is this plane\n");
	printf("flying in an insect-like pattern?\n");
	printf("Get your nose in there. Don't be afraid.\n");
	printf("Smell it. Full reverse!\n");
	printf("Just drop it. Be a part of it.\n");
	printf("Aim for the center!\n");
	printf("Now drop it in! Drop it in, woman!\n");
	printf("Oome on, already.\n");
	printf("Barry, we did it!\n");
	printf("You taught me how to fly!\n");
	printf("- Yes. No high-five!\n");
	printf("- Right.\n");
	printf("Barry, it worked!\n");
	printf("Did you see the giant flower?\n");
	printf("What giant flower? Where? Of course\n");
	printf("I saw the flower! That was genius!\n");
	printf("- Thank you.\n");
	printf("- But we're not done yet.\n");
	printf("Listen, everyone!\n");
	printf("This runway is covered\n");
	printf("with the last pollen\n");
	printf("from the last flowers\n");
	printf("available anywhere on Earth.\n");
	printf("That means this is our last chance.\n");
	printf("We're the only ones who make honey,\n");
	printf("pollinate flowers and dress like this.\n");
	printf("If we're gonna survive as a species,\n");
	printf("this is our moment! What do you say?\n");
	printf("Are we going to be bees, orjust\n");
	printf("Museum of Natural History keychains?\n");
	printf("We're bees!\n");
	printf("Keychain!\n");
	printf("Then follow me! Except Keychain.\n");
	printf("Hold on, Barry. Here.\n");
	printf("You've earned this.\n");
	printf("Yeah!\n");
	printf("I'm a Pollen Jock! And it's a perfect\n");
	printf("fit. All I gotta do are the sleeves.\n");
	printf("Oh, yeah.\n");
	printf("That's our Barry.\n");
	printf("Mom! The bees are back!\n");
	printf("If anybody needs\n");
	printf("to make a call, now's the time.\n");
	printf("I got a feeling we'll be\n");
	printf("working late tonight!\n");
	printf("Here's your change. Have a great\n");
	printf("afternoon! Oan I help who's next?\n");
	printf("Would you like some honey with that?\n");
	printf("It is bee-approved. Don't forget these.\n");
	printf("Milk, cream, cheese, it's all me.\n");
	printf("And I don't see a nickel!\n");
	printf("Sometimes I just feel\n");
	printf("like a piece of meat!\n");
	printf("I had no idea.\n");
	printf("Barry, I'm sorry.\n");
	printf("Have you got a moment?\n");
	printf("Would you excuse me?\n");
	printf("My mosquito associate will help you.\n");
	printf("Sorry I'm late.\n");
	printf("He's a lawyer too?\n");
	printf("I was already a blood-sucking parasite.\n");
	printf("All I needed was a briefcase.\n");
	printf("Have a great afternoon!\n");
	printf("Barry, I just got this huge tulip order,\n");
	printf("and I can't get them anywhere.\n");
	printf("No problem, Vannie.\n");
	printf("Just leave it to me.\n");
	printf("You're a lifesaver, Barry.\n");
	printf("Oan I help who's next?\n");
	printf("All right, scramble, jocks!\n");
	printf("It's time to fly.\n");
	printf("Thank you, Barry!\n");
	printf("That bee is living my life!\n");
	printf("Let it go, Kenny.\n");
	printf("- When will this nightmare end?!\n");
	printf("- Let it all go.\n");
	printf("- Beautiful day to fly.\n");
	printf("- Sure is.\n");
	printf("Between you and me,\n");
	printf("I was dying to get out of that office.\n");
	printf("You have got\n");
	printf("to start thinking bee, my friend.\n");
	printf("- Thinking bee!\n");
	printf("- Me?\n");
	printf("Hold it. Let's just stop\n");
	printf("for a second. Hold it.\n");
	printf("I'm sorry. I'm sorry, everyone.\n");
	printf("Oan we stop here?\n");
	printf("I'm not making a major life decision\n");
	printf("during a production number!\n");
	printf("All right. Take ten, everybody.\n");
	printf("Wrap it up, guys.\n");
	printf("I had virtually no rehearsal for that.\n");
}
